services:
  postgre:
    image: postgres:16.2-alpine3.19
    container_name: postgre_web
    volumes:
      - postgre_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks: 
      - web_network
  web:
    image: node
    command: npm run start:dev
    container_name: web_app
    volumes:
      - ./:/app
    depends_on: 
      - postgre
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - ${PORT}:3000
    networks:
      - web_network

volumes:
  postgre_volume:

networks:
  web_network:
    name: web_network
    driver: bridge